# Generated by Django 5.2.5 on 2026-04-30 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_resources', to=settings.AUTH_USER_MODEL),
        ),
    ]
