# Generated by Django 5.2.5 on 2026-04-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_average_rating_profile_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_seed',
            field=models.CharField(blank=True, default='Felix', max_length=100),
        ),
    ]
